---
title: "Project Part 2"
format: pdf
editor: source
self-contained: true
---

```{r}
#| label: load in data & libraries

library(readr)
library(tidyverse)
library(lme4)
library(nlme)
library(performance)
library(ggplot2)

df_baseball <- read_csv("https://www.dropbox.com/scl/fi/2bcvc8eabdinum2e3r9oj/statcast_pitch_swing_data_20240402_20240630.csv?rlkey=bl9kxe5o9yv017cmjssbgya3s&st=pnrx2dej&dl=1")
```





```{r}
#| label: clean data

# only keep variables of interest, drop NA obs.
df_baseball_clean <- df_baseball |>
  mutate(dist_from_cen = sqrt(hc_x^2 + hc_y^2),
         pitch_type = factor(pitch_type),
         game_type = factor(game_type),
         batter = factor(batter)) |>
  select(hit_distance_sc, pitch_type, dist_from_cen, launch_angle, launch_speed, game_type, batter) |>
  drop_na() |>
  mutate(dist_from_cen_gmc = dist_from_cen - mean(dist_from_cen),
         hit_distance_gmc = hit_distance_sc - mean(hit_distance_sc),
         launch_angle_gmc = launch_angle - mean(launch_angle),
         launch_speed_gmc = launch_speed - mean(launch_speed))

```

```{r}
#| label: EDA on variables of interest

df_baseball_clean
```

```{r}
'''modelgt <- lm(hit_distance_sc ~ game_type, data = df_baseball_clean)
summary(modelgt)


modelgt |> ggplot(aes(x=game_type, y=hit_distance_sc)) +
  geom_boxplot()'''
```




```{r}
modelpt <-  lm(hit_distance_sc ~ pitch_type, data = df_baseball_clean)
summary(modelpt)

modelpt |> ggplot(aes(x=pitch_type, y=hit_distance_sc)) +
  geom_boxplot()

plot(modelpt)

```

```{r}
modeldfg <- lm(hit_distance_sc ~ dist_from_cen_gmc, data = df_baseball_clean)
summary(modeldfg)

modeldfg |> ggplot(aes(x=dist_from_cen_gmc, y=hit_distance_sc)) +
  geom_point()

plot(modeldfg)

```

```{r}
modellag <- lm(hit_distance_sc ~ launch_angle_gmc, data = df_baseball_clean)
summary(modellag)

modellag |> ggplot(aes(x=launch_angle_gmc, y=hit_distance_sc)) +
  geom_point()

plot(modellag)
```

```{r}

modellsg <- lm(hit_distance_sc ~ launch_speed_gmc, data = df_baseball_clean)
summary(modellsg)


modellsg |> ggplot(aes(x=launch_speed_gmc, y=hit_distance_sc)) +
  geom_point()

plot(modellsg)
```


```{r}
## Finding the number of Batters and Hits
n_distinct(df_baseball_clean$batter)

## Total Number of hits per player
df_baseball_clean |>
  group_by(batter) |>
  summarize(total_hits = sum(hit_distance_sc)) |>
  summarize(average = mean(total_hits))

## Total Number of Data Points
df_baseball_clean |>
  summarize(total_hits = sum(hit_distance_sc))
```

